## Neurons & Layer

Coding by hand an artifical neural network by hand. 



In [1]:
inputs = [0.3, 0.5, 0.2]
weights = [
    [0.5, 0.2, 0.8],
    [0.2, 0.3, 0.1],
    [0.1, 0.4, 0.9]
]
baises = [0.3, 0.1, 0.3]

In [2]:
layout_outputs = []

for neuron_weigths, neron_bais in zip(weights, baises):
    # Init output
    output = 0
    # Add invidual input multiplied by the respective weigth
    for input, weight in zip(inputs, neuron_weigths):
        output += input * weight
    # Add bais to current output.
    output += neron_bais
    # Add output to layer.
    layout_outputs.append(output)

layout_outputs

[0.71, 0.32999999999999996, 0.71]

## Tensors

A **tensor** is an object that can be represented as an array.

An **array** is an ordered homologous number container. It can be of `n` dimensions. When, `n=1` we speak about 1-D array (or a list). When, `n=2` we refer to this as a matrix (not all arrays are matrices).

**Homologous** is a array property defining that number of items on each dimension should be identical. The following matrix isn't homologous because the shape isn't consistent.

```py
[
    [1,2,3],
    [4,5]
]
```

## Neuron with Numpy

Using dot product between vectors to achieve the same thing in a more performant way.

In [3]:
import numpy as np

In [4]:
inputs = np.array([0.3, 0.5, 0.2])
weights = np.array([0.5, 0.2, 0.8])
bais = 2

In [5]:
output = np.dot(inputs, weights) + bais
output

np.float64(2.41)

## Neuron layers

The same approach can also be used for network layers thanks to `numpy`. We are effectively passing a matrix (2D) as first argument and a vector a second argument (1D). `numpy` treats the matrix as a list of vectors and run the dot product against the second argument.

In [6]:
inputs = [0.3, 0.5, 0.2, 0.7]
weights = [
    [0.5, 0.2, 0.8, 0.4],
    [0.2, 0.3, 0.1, 0.1],
    [0.1, 0.4, 0.9, 0.5]
]
baises = [0.3, 0.1, 0.3]

In [7]:
outputs = np.dot(weights, inputs) + baises
outputs

array([0.99, 0.4 , 1.06])

## Matrix transposition

Transposition flips the dimension of a matrix.

In [8]:
a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

np.dot(a, b)

array([[20]])

## Batching

Instead of processing one input at the time, we can speed things up by passing batch of inputs and have them processed all at once.

Each row (or vector) in the `inputs` can be treated as a sample. For the dot product to happen, we need transpose the `weights` matrix. Matrix multiplactions applies only when left matrix has the same number of column as number of rows on the right matrix: 
* Left matrix shape: `(2, 3)`, Right matrix shape `(4, 3)`: Not OK
* Left matrix shape: `(2, 3)`, Right matrix shape `(3, 4)`: OK -> Resulting matrix shape: `(2, 4)`

Because of this, the number of samples part of the input can be increased without impacting the weights.

In [9]:
inputs = np.array([
    [0.3, 0.5, 0.2, 0.7],
    [0.2, 0.6, 0.1, 0.7]
])
weights = np.array([
    [0.5, 0.2, 0.8, 0.4],
    [0.2, 0.3, 0.1, 0.1],
    [0.1, 0.4, 0.9, 0.5]
])
baises = np.array([0.3, 0.1, 0.3])

In [10]:
np.dot(inputs, weights.T) + baises

array([[0.99, 0.4 , 1.06],
       [0.88, 0.4 , 1.  ]])

This is the reason why deep neural network always accepts and list of inputs and generate a list of predictions, even when a single prediction is needed. This is because the layers have been designed for performance.